CREATE SEQUENCE sq_pk_produtoId START 1;
CREATE SEQUENCE sq_pk_vendaId START 1;

CREATE TABLE PRODUTOS (
	id INT DEFAULT NEXTVAL('sq_pk_produtoId') NOT NULL,
	nome VARCHAR(255) NOT NULL,
	PRECO REAL NOT NULL,
	CONSTRAINT pk_idProduto PRIMARY KEY (id)
);

CREATE TABLE VENDAS(
	id INT DEFAULT NEXTVAL('sq_pk_vendaId') NOT NULL,
	quantidade INT NOT NULL,
	idProduto INT NOT NULL,
	CONSTRAINT pk_vendaId PRIMARY KEY (id),
	CONSTRAINT fk_produtoId FOREIGN KEY (idProduto) REFERENCES PRODUTOS(id)
);